"""
Django settings for eleccion project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

def parse_local_settings(data_str):
    parsed = dict([s.split('=', maxsplit=2) 
                 for s in data_str.splitlines()
                 if '=' in s])
    return dict([(k.strip(), v.strip()) for k,v in parsed.items()])

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read local file config variables (keep this file secret with chmod 600)
LOCAL_SETTINGS_FNAME = BASE_DIR / 'eleccion/.local_settings'
LOCAL_SETTINGS = {}
if Path(LOCAL_SETTINGS_FNAME).is_file():
    with Path(LOCAL_SETTINGS_FNAME).open() as f:
        LOCAL_SETTINGS = parse_local_settings(f.read())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l_0m6h*7##7ynb!glaszqkn1^5&3oppiv&g&(*)ubdn$@l#afr'
if 'SECRET_KEY' in LOCAL_SETTINGS:
    SECRET_KEY = LOCAL_SETTINGS['SECRET_KEY']


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
if 'DEBUG' in LOCAL_SETTINGS:
    DEBUG = LOCAL_SETTINGS['DEBUG']

ALLOWED_HOSTS = []
if 'ALLOWED_HOSTS' in LOCAL_SETTINGS:
    ALLOWED_HOSTS = LOCAL_SETTINGS['ALLOWED_HOSTS'].split()


# Application definition

INSTALLED_APPS = [
    'votacion.apps.VotacionConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eleccion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eleccion.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            "min_length": 4,
        },
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'
if 'TIME_ZONE' in LOCAL_SETTINGS:
    TIME_ZONE = LOCAL_SETTINGS['TIME_ZONE']

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# LOGIN_REDIRECT_URL = '/'
# LOGOUT_REDIRECT_URL = '/'
